# Generated by Django 5.0.4 on 2024-04-13 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_photo_video_delete_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='name',
        ),
    ]
